#!/usr/bin/python3
#Abrir o arquivo usuarios
#separar os valores por ","
#Escrever na tela o dicionario:
# {"nome" : "Hector", "idade" : 27, "email" : "hector.silva@4linux.com.br"}

for linha in open('usuarios.csv'):
    print(lista)
